spring:
  profiles:
    active: dev  # 激活配置
  application:
    name: spider # 服务名称
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://106.12.27.199:5432/agcim
    username: agcim
    password: agcim123
  redis: # redis配置
    host: 106.12.27.199
    port: 6379
    password: agcim-2020
    database: 0

server:
  port: 8091     # 服务端口
  servlet:
    context-path: /${spring.application.name}  # 服务uri


# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath*:org/example/spider/mapper/**/*Mapper.xml
  type-aliases-package: org.example.spider.domain.*

