# ------------------------------  服务配置 ----------------------------------------------
server:
  port: 8091     # 服务端口
  servlet:
    context-path: /${spring.application.name}  # 服务uri

# ----------------------------- spring 配置 --------------------------------------------
spring:
  profiles:
    active: dev  # 激活配置
  application:
    name: spider # 服务名称
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://106.12.27.199:5432/agcim
    username: agcim
    password: agcim123
  redis: # redis配置
    host: 106.12.27.199
    port: 6379
    password: agcim-2020
    database: 0
  kafka: # kafka 配置
    bootstrap-servers: 106.12.27.199:9092
    consumer:
      group-id: system.log.topic
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest # 设置消费者分组最初的消费进度为 earliest
      properties:
        spring:
          json:
            trusted:
              packages: org.example.spider.domain  # 指定序列化的包，必须
      # Kafka Consumer Listener 监听器配置
      listener:
        missing-topics-fatal: false # 消费监听接口监听的主题不存在时，默认会报错。所以通过设置为 false ，解决报错
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: other-topic
  rabbitmq: # rabbitmq配置
    host: 106.12.27.199
    port: 5672
    username: admin
    password: admin



# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath*:org/example/spider/mapper/**/*Mapper.xml
  type-aliases-package: org.example.spider.domain.*

# ****************************************** person base config *******************************************************
# RabbitMQ queue config
mq:
  direct:
    queue: mq.direct.queue
    exchange: mq.direct.exchange
    routekey: mq.direct.routekey
# kafka topic config